# Generated by Django 3.2 on 2021-04-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data1', models.IntegerField(default=0)),
                ('data2', models.IntegerField(default=0)),
                ('data3', models.IntegerField(default=0)),
            ],
        ),
    ]
